<?php

namespace Database\Seeders;

use App\Models\Config\Pais;
use Illuminate\Database\Seeder;

class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Información tomada de: https://gist.github.com/angeldelrio/1fbf4d54cd62b30fa68c
     * En caso de requerir más información de países, recomiendo revisar: https://github.com/webpatser/laravel-countries
     * @return void
     */
    public function run()
    {
        $countries = [
            ['id' => 1,  'short_description' => 'AF', 'long_description' => 'Afganistán'],
            ['id' => 2,  'short_description' => 'AX', 'long_description' => 'Islas Gland'],
            ['id' => 3,  'short_description' => 'AL', 'long_description' => 'Albania'],
            ['id' => 4,  'short_description' => 'DE', 'long_description' => 'Alemania'],
            ['id' => 5,  'short_description' => 'AD', 'long_description' => 'Andorra'],
            ['id' => 6,  'short_description' => 'AO', 'long_description' => 'Angola'],
            ['id' => 7,  'short_description' => 'AI', 'long_description' => 'Anguilla'],
            ['id' => 8,  'short_description' => 'AQ', 'long_description' => 'Antártida'],
            ['id' => 9,  'short_description' => 'AG', 'long_description' => 'Antigua y Barbuda'],
            ['id' => 10, 'short_description' => 'AN', 'long_description' =>  'Antillas Holandesas'],
            ['id' => 11, 'short_description' => 'SA', 'long_description' =>  'Arabia Saudí'],
            ['id' => 12, 'short_description' => 'DZ', 'long_description' =>  'Argelia'],
            ['id' => 13, 'short_description' => 'AR', 'long_description' =>  'Argentina'],
            ['id' => 14, 'short_description' => 'AM', 'long_description' =>  'Armenia'],
            ['id' => 15, 'short_description' => 'AW', 'long_description' =>  'Aruba'],
            ['id' => 16, 'short_description' => 'AU', 'long_description' =>  'Australia'],
            ['id' => 17, 'short_description' => 'AT', 'long_description' =>  'Austria'],
            ['id' => 18, 'short_description' => 'AZ', 'long_description' =>  'Azerbaiyán'],
            ['id' => 19, 'short_description' => 'BS', 'long_description' =>  'Bahamas'],
            ['id' => 20, 'short_description' => 'BH', 'long_description' =>  'Bahréin'],
            ['id' => 21, 'short_description' => 'BD', 'long_description' =>  'Bangladesh'],
            ['id' => 22, 'short_description' => 'BB', 'long_description' =>  'Barbados'],
            ['id' => 23, 'short_description' => 'BY', 'long_description' =>  'Bielorrusia'],
            ['id' => 24, 'short_description' => 'BE', 'long_description' =>  'Bélgica'],
            ['id' => 25, 'short_description' => 'BZ', 'long_description' =>  'Belice'],
            ['id' => 26, 'short_description' => 'BJ', 'long_description' =>  'Benin'],
            ['id' => 27, 'short_description' => 'BM', 'long_description' =>  'Bermudas'],
            ['id' => 28, 'short_description' => 'BT', 'long_description' =>  'Bhután'],
            ['id' => 29, 'short_description' => 'BO', 'long_description' =>  'Bolivia'],
            ['id' => 30, 'short_description' => 'BA', 'long_description' =>  'Bosnia y Herzegovina'],
            ['id' => 31, 'short_description' => 'BW', 'long_description' =>  'Botsuana'],
            ['id' => 32, 'short_description' => 'BV', 'long_description' =>  'Isla Bouvet'],
            ['id' => 33, 'short_description' => 'BR', 'long_description' =>  'Brasil'],
            ['id' => 34, 'short_description' => 'BN', 'long_description' =>  'Brunéi'],
            ['id' => 35, 'short_description' => 'BG', 'long_description' =>  'Bulgaria'],
            ['id' => 36, 'short_description' => 'BF', 'long_description' =>  'Burkina Faso'],
            ['id' => 37, 'short_description' => 'BI', 'long_description' =>  'Burundi'],
            ['id' => 38, 'short_description' => 'CV', 'long_description' =>  'Cabo Verde'],
            ['id' => 39, 'short_description' => 'KY', 'long_description' =>  'Islas Caimán'],
            ['id' => 40, 'short_description' => 'KH', 'long_description' =>  'Camboya'],
            ['id' => 41, 'short_description' => 'CM', 'long_description' =>  'Camerún'],
            ['id' => 42, 'short_description' => 'CA', 'long_description' =>  'Canadá'],
            ['id' => 43, 'short_description' => 'CF', 'long_description' =>  'República Centroafricana'],
            ['id' => 44, 'short_description' => 'TD', 'long_description' =>  'Chad'],
            ['id' => 45, 'short_description' => 'CZ', 'long_description' =>  'República Checa'],
            ['id' => 46, 'short_description' => 'CL', 'long_description' =>  'Chile'],
            ['id' => 47, 'short_description' => 'CN', 'long_description' =>  'China'],
            ['id' => 48, 'short_description' => 'CY', 'long_description' =>  'Chipre'],
            ['id' => 49, 'short_description' => 'CX', 'long_description' =>  'Isla de Navidad'],
            ['id' => 50, 'short_description' => 'VA', 'long_description' =>  'Ciudad del Vaticano'],
            ['id' => 51, 'short_description' => 'CC', 'long_description' =>  'Islas Cocos'],
            ['id' => 52, 'short_description' => 'CO', 'long_description' =>  'Colombia'],
            ['id' => 53, 'short_description' => 'KM', 'long_description' =>  'Comoras'],
            ['id' => 54, 'short_description' => 'CD', 'long_description' =>  'República Democrática del Congo'],
            ['id' => 55, 'short_description' => 'CG', 'long_description' =>  'Congo'],
            ['id' => 56, 'short_description' => 'CK', 'long_description' =>  'Islas Cook'],
            ['id' => 57, 'short_description' => 'KP', 'long_description' =>  'Corea del Norte'],
            ['id' => 58, 'short_description' => 'KR', 'long_description' =>  'Corea del Sur'],
            ['id' => 59, 'short_description' => 'CI', 'long_description' =>  'Costa de Marfil'],
            ['id' => 60, 'short_description' => 'CR', 'long_description' =>  'Costa Rica'],
            ['id' => 61, 'short_description' => 'HR', 'long_description' =>  'Croacia'],
            ['id' => 62, 'short_description' => 'CU', 'long_description' =>  'Cuba'],
            ['id' => 63, 'short_description' => 'DK', 'long_description' =>  'Dinamarca'],
            ['id' => 64, 'short_description' => 'DM', 'long_description' =>  'Dominica'],
            ['id' => 65, 'short_description' => 'DO', 'long_description' =>  'República Dominicana'],
            ['id' => 66, 'short_description' => 'EC', 'long_description' =>  'Ecuador'],
            ['id' => 67, 'short_description' => 'EG', 'long_description' =>  'Egipto'],
            ['id' => 68, 'short_description' => 'SV', 'long_description' =>  'El Salvador'],
            ['id' => 69, 'short_description' => 'AE', 'long_description' =>  'Emiratos Árabes Unidos'],
            ['id' => 70, 'short_description' => 'ER', 'long_description' =>  'Eritrea'],
            ['id' => 71, 'short_description' => 'SK', 'long_description' =>  'Eslovaquia'],
            ['id' => 72, 'short_description' => 'SI', 'long_description' =>  'Eslovenia'],
            ['id' => 73, 'short_description' => 'ES', 'long_description' =>  'España'],
            ['id' => 74, 'short_description' => 'UM', 'long_description' =>  'Islas ultramarinas de Estados Unidos'],
            ['id' => 75, 'short_description' => 'US', 'long_description' =>  'Estados Unidos'],
            ['id' => 76, 'short_description' => 'EE', 'long_description' =>  'Estonia'],
            ['id' => 77, 'short_description' => 'ET', 'long_description' =>  'Etiopía'],
            ['id' => 78, 'short_description' => 'FO', 'long_description' =>  'Islas Feroe'],
            ['id' => 79, 'short_description' => 'PH', 'long_description' =>  'Filipinas'],
            ['id' => 80, 'short_description' => 'FI', 'long_description' =>  'Finlandia'],
            ['id' => 81, 'short_description' => 'FJ', 'long_description' =>  'Fiyi'],
            ['id' => 82, 'short_description' => 'FR', 'long_description' =>  'Francia'],
            ['id' => 83, 'short_description' => 'GA', 'long_description' =>  'Gabón'],
            ['id' => 84, 'short_description' => 'GM', 'long_description' =>  'Gambia'],
            ['id' => 85, 'short_description' => 'GE', 'long_description' =>  'Georgia'],
            ['id' => 86, 'short_description' => 'GS', 'long_description' =>  'Islas Georgias del Sur y Sandwich del Sur'],
            ['id' => 87, 'short_description' => 'GH', 'long_description' =>  'Ghana'],
            ['id' => 88, 'short_description' => 'GI', 'long_description' =>  'Gibraltar'],
            ['id' => 89, 'short_description' => 'GD', 'long_description' =>  'Granada'],
            ['id' => 90, 'short_description' => 'GR', 'long_description' =>  'Grecia'],
            ['id' => 91, 'short_description' => 'GL', 'long_description' =>  'Groenlandia'],
            ['id' => 92, 'short_description' => 'GP', 'long_description' =>  'Guadalupe'],
            ['id' => 93, 'short_description' => 'GU', 'long_description' =>  'Guam'],
            ['id' => 94, 'short_description' => 'GT', 'long_description' =>  'Guatemala'],
            ['id' => 95, 'short_description' => 'GF', 'long_description' =>  'Guayana Francesa'],
            ['id' => 96, 'short_description' => 'GN', 'long_description' =>  'Guinea'],
            ['id' => 97, 'short_description' => 'GQ', 'long_description' =>  'Guinea Ecuatorial'],
            ['id' => 98, 'short_description' => 'GW', 'long_description' =>  'Guinea-Bissau'],
            ['id' => 99, 'short_description' => 'GY', 'long_description' =>  'Guyana'],
            ['id' => 100, 'short_description' => 'HT', 'long_description' =>  'Haití'],
            ['id' => 101, 'short_description' => 'HM', 'long_description' =>  'Islas Heard y McDonald'],
            ['id' => 102, 'short_description' => 'HN', 'long_description' =>  'Honduras'],
            ['id' => 103, 'short_description' => 'HK', 'long_description' =>  'Hong Kong'],
            ['id' => 104, 'short_description' => 'HU', 'long_description' =>  'Hungría'],
            ['id' => 105, 'short_description' => 'IN', 'long_description' =>  'India'],
            ['id' => 106, 'short_description' => 'ID', 'long_description' =>  'Indonesia'],
            ['id' => 107, 'short_description' => 'IR', 'long_description' =>  'Irán'],
            ['id' => 108, 'short_description' => 'IQ', 'long_description' =>  'Iraq'],
            ['id' => 109, 'short_description' => 'IE', 'long_description' =>  'Irlanda'],
            ['id' => 110, 'short_description' => 'IS', 'long_description' =>  'Islandia'],
            ['id' => 111, 'short_description' => 'IL', 'long_description' =>  'Israel'],
            ['id' => 112, 'short_description' => 'IT', 'long_description' =>  'Italia'],
            ['id' => 113, 'short_description' => 'JM', 'long_description' =>  'Jamaica'],
            ['id' => 114, 'short_description' => 'JP', 'long_description' =>  'Japón'],
            ['id' => 115, 'short_description' => 'JO', 'long_description' =>  'Jordania'],
            ['id' => 116, 'short_description' => 'KZ', 'long_description' =>  'Kazajstán'],
            ['id' => 117, 'short_description' => 'KE', 'long_description' =>  'Kenia'],
            ['id' => 118, 'short_description' => 'KG', 'long_description' =>  'Kirguistán'],
            ['id' => 119, 'short_description' => 'KI', 'long_description' =>  'Kiribati'],
            ['id' => 120, 'short_description' => 'KW', 'long_description' => 'Kuwait'],
            ['id' => 121, 'short_description' => 'LA', 'long_description' => 'Laos'],
            ['id' => 122, 'short_description' => 'LS', 'long_description' => 'Lesotho'],
            ['id' => 123, 'short_description' => 'LV', 'long_description' => 'Letonia'],
            ['id' => 124, 'short_description' => 'LB', 'long_description' => 'Líbano'],
            ['id' => 125, 'short_description' => 'LR', 'long_description' => 'Liberia'],
            ['id' => 126, 'short_description' => 'LY', 'long_description' => 'Libia'],
            ['id' => 127, 'short_description' => 'LI', 'long_description' => 'Liechtenstein'],
            ['id' => 128, 'short_description' => 'LT', 'long_description' => 'Lituania'],
            ['id' => 129, 'short_description' => 'LU', 'long_description' => 'Luxemburgo'],
            ['id' => 130, 'short_description' => 'MO', 'long_description' => 'Macao'],
            ['id' => 131, 'short_description' => 'MK', 'long_description' => 'ARY Macedonia'],
            ['id' => 132, 'short_description' => 'MG', 'long_description' => 'Madagascar'],
            ['id' => 133, 'short_description' => 'MY', 'long_description' => 'Malasia'],
            ['id' => 134, 'short_description' => 'MW', 'long_description' => 'Malawi'],
            ['id' => 135, 'short_description' => 'MV', 'long_description' => 'Maldivas'],
            ['id' => 136, 'short_description' => 'ML', 'long_description' => 'Malí'],
            ['id' => 137, 'short_description' => 'MT', 'long_description' => 'Malta'],
            ['id' => 138, 'short_description' => 'FK', 'long_description' => 'Islas Malvinas'],
            ['id' => 139, 'short_description' => 'MP', 'long_description' => 'Islas Marianas del Norte'],
            ['id' => 140, 'short_description' => 'MA', 'long_description' => 'Marruecos'],
            ['id' => 141, 'short_description' => 'MH', 'long_description' => 'Islas Marshall'],
            ['id' => 142, 'short_description' => 'MQ', 'long_description' => 'Martinica'],
            ['id' => 143, 'short_description' => 'MU', 'long_description' => 'Mauricio'],
            ['id' => 144, 'short_description' => 'MR', 'long_description' => 'Mauritania'],
            ['id' => 145, 'short_description' => 'YT', 'long_description' => 'Mayotte'],
            ['id' => 146, 'short_description' => 'MX', 'long_description' => 'México'],
            ['id' => 147, 'short_description' => 'FM', 'long_description' => 'Micronesia'],
            ['id' => 148, 'short_description' => 'MD', 'long_description' => 'Moldavia'],
            ['id' => 149, 'short_description' => 'MC', 'long_description' => 'Mónaco'],
            ['id' => 150, 'short_description' => 'MN', 'long_description' => 'Mongolia'],
            ['id' => 151, 'short_description' => 'MS', 'long_description' => 'Montserrat'],
            ['id' => 152, 'short_description' => 'MZ', 'long_description' => 'Mozambique'],
            ['id' => 153, 'short_description' => 'MM', 'long_description' => 'Myanmar'],
            ['id' => 154, 'short_description' => 'NA', 'long_description' => 'Namibia'],
            ['id' => 155, 'short_description' => 'NR', 'long_description' => 'Nauru'],
            ['id' => 156, 'short_description' => 'NP', 'long_description' => 'Nepal'],
            ['id' => 157, 'short_description' => 'NI', 'long_description' => 'Nicaragua'],
            ['id' => 158, 'short_description' => 'NE', 'long_description' => 'Níger'],
            ['id' => 159, 'short_description' => 'NG', 'long_description' => 'Nigeria'],
            ['id' => 160, 'short_description' => 'NU', 'long_description' => 'Niue'],
            ['id' => 161, 'short_description' => 'NF', 'long_description' => 'Isla Norfolk'],
            ['id' => 162, 'short_description' => 'NO', 'long_description' => 'Noruega'],
            ['id' => 163, 'short_description' => 'NC', 'long_description' => 'Nueva Caledonia'],
            ['id' => 164, 'short_description' => 'NZ', 'long_description' => 'Nueva Zelanda'],
            ['id' => 165, 'short_description' => 'OM', 'long_description' => 'Omán'],
            ['id' => 166, 'short_description' => 'NL', 'long_description' => 'Países Bajos'],
            ['id' => 167, 'short_description' => 'PK', 'long_description' => 'Pakistán'],
            ['id' => 168, 'short_description' => 'PW', 'long_description' => 'Palau'],
            ['id' => 169, 'short_description' => 'PS', 'long_description' => 'Palestina'],
            ['id' => 170, 'short_description' => 'PA', 'long_description' => 'Panamá'],
            ['id' => 171, 'short_description' => 'PG', 'long_description' => 'Papúa Nueva Guinea'],
            ['id' => 172, 'short_description' => 'PY', 'long_description' => 'Paraguay'],
            ['id' => 173, 'short_description' => 'PE', 'long_description' => 'Perú'],
            ['id' => 174, 'short_description' => 'PN', 'long_description' => 'Islas Pitcairn'],
            ['id' => 175, 'short_description' => 'PF', 'long_description' => 'Polinesia Francesa'],
            ['id' => 176, 'short_description' => 'PL', 'long_description' => 'Polonia'],
            ['id' => 177, 'short_description' => 'PT', 'long_description' => 'Portugal'],
            ['id' => 178, 'short_description' => 'PR', 'long_description' => 'Puerto Rico'],
            ['id' => 179, 'short_description' => 'QA', 'long_description' => 'Qatar'],
            ['id' => 180, 'short_description' => 'GB', 'long_description' => 'Reino Unido'],
            ['id' => 181, 'short_description' => 'RE', 'long_description' => 'Reunión'],
            ['id' => 182, 'short_description' => 'RW', 'long_description' => 'Ruanda'],
            ['id' => 183, 'short_description' => 'RO', 'long_description' => 'Rumania'],
            ['id' => 184, 'short_description' => 'RU', 'long_description' => 'Rusia'],
            ['id' => 185, 'short_description' => 'EH', 'long_description' => 'Sahara Occidental'],
            ['id' => 186, 'short_description' => 'SB', 'long_description' => 'Islas Salomón'],
            ['id' => 187, 'short_description' => 'WS', 'long_description' => 'Samoa'],
            ['id' => 188, 'short_description' => 'AS', 'long_description' => 'Samoa Americana'],
            ['id' => 189, 'short_description' => 'KN', 'long_description' => 'San Cristóbal y Nevis'],
            ['id' => 190, 'short_description' => 'SM', 'long_description' => 'San Marino'],
            ['id' => 191, 'short_description' => 'PM', 'long_description' => 'San Pedro y Miquelón'],
            ['id' => 192, 'short_description' => 'VC', 'long_description' => 'San Vicente y las Granadinas'],
            ['id' => 193, 'short_description' => 'SH', 'long_description' => 'Santa Helena'],
            ['id' => 194, 'short_description' => 'LC', 'long_description' => 'Santa Lucía'],
            ['id' => 195, 'short_description' => 'ST', 'long_description' => 'Santo Tomé y Príncipe'],
            ['id' => 196, 'short_description' => 'SN', 'long_description' => 'Senegal'],
            ['id' => 197, 'short_description' => 'CS', 'long_description' => 'Serbia y Montenegro'],
            ['id' => 198, 'short_description' => 'SC', 'long_description' => 'Seychelles'],
            ['id' => 199, 'short_description' => 'SL', 'long_description' => 'Sierra Leona'],
            ['id' => 200, 'short_description' => 'SG', 'long_description' => 'Singapur'],
            ['id' => 201, 'short_description' => 'SY', 'long_description' => 'Siria'],
            ['id' => 202, 'short_description' => 'SO', 'long_description' => 'Somalia'],
            ['id' => 203, 'short_description' => 'LK', 'long_description' => 'Sri Lanka'],
            ['id' => 204, 'short_description' => 'SZ', 'long_description' => 'Suazilandia'],
            ['id' => 205, 'short_description' => 'ZA', 'long_description' => 'Sudáfrica'],
            ['id' => 206, 'short_description' => 'SD', 'long_description' => 'Sudán'],
            ['id' => 207, 'short_description' => 'SE', 'long_description' => 'Suecia'],
            ['id' => 208, 'short_description' => 'CH', 'long_description' => 'Suiza'],
            ['id' => 209, 'short_description' => 'SR', 'long_description' => 'Surinam'],
            ['id' => 210, 'short_description' => 'SJ', 'long_description' => 'Svalbard y Jan Mayen'],
            ['id' => 211, 'short_description' => 'TH', 'long_description' => 'Tailandia'],
            ['id' => 212, 'short_description' => 'TW', 'long_description' => 'Taiwán'],
            ['id' => 213, 'short_description' => 'TZ', 'long_description' => 'Tanzania'],
            ['id' => 214, 'short_description' => 'TJ', 'long_description' => 'Tayikistán'],
            ['id' => 215, 'short_description' => 'IO', 'long_description' => 'Territorio Británico del Océano Índico'],
            ['id' => 216, 'short_description' => 'TF', 'long_description' => 'Territorios Australes Franceses'],
            ['id' => 217, 'short_description' => 'TL', 'long_description' => 'Timor Oriental'],
            ['id' => 218, 'short_description' => 'TG', 'long_description' => 'Togo'],
            ['id' => 219, 'short_description' => 'TK', 'long_description' => 'Tokelau'],
            ['id' => 220, 'short_description' => 'TO', 'long_description' => 'Tonga'],
            ['id' => 221, 'short_description' => 'TT', 'long_description' => 'Trinidad y Tobago'],
            ['id' => 222, 'short_description' => 'TN', 'long_description' => 'Túnez'],
            ['id' => 223, 'short_description' => 'TC', 'long_description' => 'Islas Turcas y Caicos'],
            ['id' => 224, 'short_description' => 'TM', 'long_description' => 'Turkmenistán'],
            ['id' => 225, 'short_description' => 'TR', 'long_description' => 'Turquía'],
            ['id' => 226, 'short_description' => 'TV', 'long_description' => 'Tuvalu'],
            ['id' => 227, 'short_description' => 'UA', 'long_description' => 'Ucrania'],
            ['id' => 228, 'short_description' => 'UG', 'long_description' => 'Uganda'],
            ['id' => 229, 'short_description' => 'UY', 'long_description' => 'Uruguay'],
            ['id' => 230, 'short_description' => 'UZ', 'long_description' => 'Uzbekistán'],
            ['id' => 231, 'short_description' => 'VU', 'long_description' => 'Vanuatu'],
            ['id' => 232, 'short_description' => 'VE', 'long_description' => 'Venezuela'],
            ['id' => 233, 'short_description' => 'VN', 'long_description' => 'Vietnam'],
            ['id' => 234, 'short_description' => 'VG', 'long_description' => 'Islas Vírgenes Británicas'],
            ['id' => 235, 'short_description' => 'VI', 'long_description' => 'Islas Vírgenes de los Estados Unidos'],
            ['id' => 236, 'short_description' => 'WF', 'long_description' => 'Wallis y Futuna'],
            ['id' => 237, 'short_description' => 'YE', 'long_description' => 'Yemen'],
            ['id' => 238, 'short_description' => 'DJ', 'long_description' => 'Yibuti'],
            ['id' => 239, 'short_description' => 'ZM', 'long_description' => 'Zambia'],
            ['id' => 240, 'short_description' => 'ZW', 'long_description' => 'Zimbabue'],
        ];

        foreach ($countries as $country) {
            Pais::create([
                'nombre' => trim($country['long_description']),
                'codigo' => mb_strtoupper(trim($country['short_description'])),
                'orden' =>  $country['id'],
            ]);
        }
    }
}
